/**
 * Auto-generated HTML content manifest
 * Generated by extract_html_content.py
 * DO NOT EDIT MANUALLY
 */

// List of menu tab IDs that have HTML content
export const menuTabIds = [
  'lunch',
];